package com.reconstruct.model.standard;

import java.util.LinkedHashMap;
import java.util.Map;

public class PN02 {
    private PN02() { }

    public static Map<String, Double> MINIMAL_CORROSION_COVER_THICKNESS_FOR_REINFORCEMENT_STANDARD_STEEL_MM = new LinkedHashMap<>();
    static {
        MINIMAL_CORROSION_COVER_THICKNESS_FOR_REINFORCEMENT_STANDARD_STEEL_MM.put("X0", 10d);
        MINIMAL_CORROSION_COVER_THICKNESS_FOR_REINFORCEMENT_STANDARD_STEEL_MM.put("XC1", 15d);
        MINIMAL_CORROSION_COVER_THICKNESS_FOR_REINFORCEMENT_STANDARD_STEEL_MM.put("XC2/XC3", 20d);
        MINIMAL_CORROSION_COVER_THICKNESS_FOR_REINFORCEMENT_STANDARD_STEEL_MM.put("XC4", 25d);
        MINIMAL_CORROSION_COVER_THICKNESS_FOR_REINFORCEMENT_STANDARD_STEEL_MM.put("XD1/XD2,XD3", 40d);
        MINIMAL_CORROSION_COVER_THICKNESS_FOR_REINFORCEMENT_STANDARD_STEEL_MM.put("XS1/XS2/XS3", 40d);
    }

    public static Map<String, Double> MINIMAL_CORROSION_COVER_THICKNESS_FOR_REINFORCEMENT_PRESTRESSED_STEEL_MM = new LinkedHashMap<>();
    static {
        MINIMAL_CORROSION_COVER_THICKNESS_FOR_REINFORCEMENT_PRESTRESSED_STEEL_MM.put("X0", 15d);
        MINIMAL_CORROSION_COVER_THICKNESS_FOR_REINFORCEMENT_PRESTRESSED_STEEL_MM.put("XC1", 20d);
        MINIMAL_CORROSION_COVER_THICKNESS_FOR_REINFORCEMENT_PRESTRESSED_STEEL_MM.put("XC2/XC3", 30d);
        MINIMAL_CORROSION_COVER_THICKNESS_FOR_REINFORCEMENT_PRESTRESSED_STEEL_MM.put("XC4", 35d);
        MINIMAL_CORROSION_COVER_THICKNESS_FOR_REINFORCEMENT_PRESTRESSED_STEEL_MM.put("XD1/XD2,XD3", 50d);
        MINIMAL_CORROSION_COVER_THICKNESS_FOR_REINFORCEMENT_PRESTRESSED_STEEL_MM.put("XS1/XS2/XS3", 50d);
    }

    public static Map<String, Double> COMPRESSION_CALCULATION_MPA_VALUES_OF_REINFORCED_CONCRETE = new LinkedHashMap<>();
    static {
        COMPRESSION_CALCULATION_MPA_VALUES_OF_REINFORCED_CONCRETE.put("B15", 8.0d);
        COMPRESSION_CALCULATION_MPA_VALUES_OF_REINFORCED_CONCRETE.put("B20", 10.6d);
        COMPRESSION_CALCULATION_MPA_VALUES_OF_REINFORCED_CONCRETE.put("B25", 13.3d);
        COMPRESSION_CALCULATION_MPA_VALUES_OF_REINFORCED_CONCRETE.put("B30", 16.7d);
        COMPRESSION_CALCULATION_MPA_VALUES_OF_REINFORCED_CONCRETE.put("B37", 20.0d);
        COMPRESSION_CALCULATION_MPA_VALUES_OF_REINFORCED_CONCRETE.put("B45", 23.3d);
        COMPRESSION_CALCULATION_MPA_VALUES_OF_REINFORCED_CONCRETE.put("B50", 26.7d);
        COMPRESSION_CALCULATION_MPA_VALUES_OF_REINFORCED_CONCRETE.put("B55", 30.0d);
        COMPRESSION_CALCULATION_MPA_VALUES_OF_REINFORCED_CONCRETE.put("B60", 33.3d);
    }

    public static Map<String, Double> YIELD_STRENGTH_CALCULATION_MPA_VALUES_OF_REINFORCEMENT_STEEL = new LinkedHashMap<>();
    static {
        YIELD_STRENGTH_CALCULATION_MPA_VALUES_OF_REINFORCEMENT_STEEL.put("A-0", 190.0d);
        YIELD_STRENGTH_CALCULATION_MPA_VALUES_OF_REINFORCEMENT_STEEL.put("A-I", 210.0d);
        YIELD_STRENGTH_CALCULATION_MPA_VALUES_OF_REINFORCEMENT_STEEL.put("A-II", 310.0d);
        YIELD_STRENGTH_CALCULATION_MPA_VALUES_OF_REINFORCEMENT_STEEL.put("A-III", 350.0d);
        YIELD_STRENGTH_CALCULATION_MPA_VALUES_OF_REINFORCEMENT_STEEL.put("A-IIIN", 420.0d);
    }
}
